[package]
name = "textutils"
version = "0.1.0"
edition = "2021"

[dependencies]
icu = { version = "1.5.0", features = [
    "compiled_data"
] }
once_cell = "1.20.2"
unicase = "2.8.0"
unicode-normalization = "0.1.24"
